### PR TITLE
Steer assist.

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
Drive pen down hard while turning. This makes for more precise turn
as pen acts as a pivot, and also makes lets the wheels slip easier.

### CODE REVIEW

**Comment by IlyaSukhanov** [comment]
@mpavlov I didn't quite grok why we bother keeping state in CheezoidPenControl, is this work around for non-blocking move command?

**Comment by mpavlov** [comment]
Nah, I don't think it was related to non-blocking. Might have been in order to disallow the sending of pen up/down commands to the servo without any wheel movement.

**Comment by mpavlov** [comment]
steer assist looks good :+1: 

If you haven't already, check whether you can do a `self.pen_servo.stop_servo` on an already stopped servo. Doing this on Fri raised an error so that's why you probably saw more `if`s than you expected here. :)

**Comment by IlyaSukhanov** [comment]
Tried multiple stops. It seemed to work. I'll leave some of the other conditionals in.

**Pull request merged**
